services:
  backend:
    build:
      context: ./sub-manager-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./sub-manager-backend:/app
      - ~/.m2:/root/.m2
    environment:
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
      - SPRING_PROFILES_ACTIVE=dev

      # Those envs are only for dev purposes:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword 
      - JWT_SECRET=Hg7GFFGmMETEty+af3KNLD48u0o/f/vMNo9d3R1p/Pw=
      - JWT_EXP_TIME=86400000
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./sub-manager-front-end
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./sub-manager-front-end
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./sub-manager-front-end/package.json
          target: /app/package.json
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=gabrielgaleza@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  node_modules:
  pgadmin_data: